Navbar implementation
TritonSE/TAP-Foster-Dog-Matching pull request #10
Opened 2022-01-18 04:11 UTC by parth4apple

### Administrative Info
[GitHub Issue 2]

### Changes
Added styled-components to package.json for component styling
Created Navbar Component and its styling based on the figma model
Used the Navbar Component in the jsx of Landing.js, Foster.js, Dashboard.js, and Calendar.js files 

### Testing
The changes I made look and behave like the figma model

### Confirmation of Change 
<img width="1792" alt="navbar" src="https://user-images.githubusercontent.com/72187062/149869573-2e21dccf-42c3-41dc-9df5-a35664aaec66.png">

https://user-images.githubusercontent.com/72187062/149869581-95c25485-9d6c-445e-95bf-cc21d7b60165.mov

2022-01-19 01:06 UTC, portoaj commented
Can you remove your changes to all the pages, and just push the Navbar/ Navbar Styled components. One issue with this commit is that it is going to conflict with my updates to the dashboard page.

2022-02-06 06:37 UTC, dnanjunda requested changes
Nice job Parth! This looks good overall but there's a couple things to fix:

1. I think the web navbar here is a bit too wide. Make sure the width matches whatever is specified on Figma. 
<img width="1440" alt="navbar" src="https://user-images.githubusercontent.com/57281768/152669843-b52496c8-bf2d-4c02-b2e4-96cb73c8445d.png">

2. Right now the text doesn't look great when window width is small. Use vw/vh for font size so that it is responsive to resizing. You can use on online converter to convert px to vw/vh.
<img width="763" alt="navbar_font" src="https://user-images.githubusercontent.com/57281768/152669906-d4841efc-1839-45c0-af83-0c1964be687f.png">

3. For some of the mobile widths, the navbar's position is a bit off. Make sure it looks good for all the different devices in inspect element.
<img width="333" alt="navbar_mobile" src="https://user-images.githubusercontent.com/57281768/152670126-c6194604-f2ef-4754-9a7a-bc85bdf40a0e.png">

4. Can you add a "Sign Out" button at the bottom of the navbar for mobile, like in the designs?
5. Right now you have a .js file for your navbar css which is fine, but just to maintain consistency with the rest of the project and TSE in general, make a Navbar.css file in the css folder and put all the navbar related css in there.

2022-02-09 02:11 UTC, dnanjunda reviewed
Almost there Parth! Just a couple small things:

1. I don't think you moved the css code for the navbar from your .js file to a .css file in the css folder. Please do this.
2. This is a minor thing, but can you add a slide out animation for the mobile navbar when it is open and the hamburger icon is clicked, similar to the slide in you already have? If it's hard to do, don't worry about it.

2022-02-09 22:11 UTC, petabite commented on client/package.json
> +    "package.json": "^2.0.1",
```suggestion
```

2022-02-09 22:22 UTC, petabite requested changes
Nice, looking good! Everything is responsive on my end and is working as expected. Left a couple of comments for some small things below. Should be quick fixes.

2022-02-09 22:22 UTC, petabite commented on client/package.json
> +    "package.json": "^2.0.1",
```suggestion
```

2022-02-09 22:22 UTC, petabite commented on client/src/components/Navbar.js
> +  }
extra curly bracket?

2022-02-09 22:22 UTC, petabite commented on client/src/components/Navbar.js
> +}
here too

2022-02-09 22:22 UTC, petabite commented on package.json
> +    "styled-components": "^5.3.3"
```suggestion
```
I think you may have accidentally installed `styled-components` in the root folder. Can you run `npm uninstall` on this? This should also resolve the merge conflict you have.

2022-02-10 04:23 UTC, dnanjunda approved these changes
LGTM. Great job Parth!

2022-02-10 05:10 UTC, petabite approved these changes
👌

2022-02-10 20:19 UTC, merged