contact page
TritonSE/TAP-Foster-Dog-Matching pull request #17
Opened 2022-01-25 18:37 UTC by parth4apple

### Administrative Info
[GitHub Issue #14]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
I implemented the contact page and its styling. The page is responsive to different screen sizes.

### Testing
How did you confirm your changes worked? 
The page has the same behavior as the figma model.

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
<img width="1791" alt="Screen Shot 2022-01-25 at 10 36 22 AM" src="https://user-images.githubusercontent.com/72187062/151038085-5f9f011c-50d0-431e-9ad2-fda376f303ad.png">
<img width="1789" alt="Screen Shot 2022-01-25 at 10 36 40 AM" src="https://user-images.githubusercontent.com/72187062/151038132-cb9cdd2e-821d-4caa-8f27-2a7bf8a88ec3.png">

2022-02-15 02:21 UTC, dnanjunda requested changes
1. This isn't super important, but can you make the background color for the dropdown gray instead of white, like in the designs?
2. Add a bit more padding for the "continue" button. It should be similar to the "send" button on the other screen.

Your code:
<img width="588" alt="continue" src="https://user-images.githubusercontent.com/57281768/153979623-d93a3248-88ab-473c-b7c1-9e2c40b00a44.png">
Figma:
<img width="388" alt="continue_figma" src="https://user-images.githubusercontent.com/57281768/153979656-970a8437-9be6-4308-bdf9-f84cb3645d43.png">

3. For most of the mobile screens, the text is way too big. Also, try to reduce the height of the component with the message box.
<img width="342" alt="contact_mobile" src="https://user-images.githubusercontent.com/57281768/153979976-962ff53e-e753-43cb-996e-bf6fae99e127.png">


4. Everything seems a bit too big to me. Make sure all the components/text you use are responsive.
<img width="1440" alt="contact" src="https://user-images.githubusercontent.com/57281768/153980240-5e936776-eba0-4f65-b554-a2b90efb9088.png">


5. Merge main with your branch so that you have the navbar for this page.

2022-02-22 08:56 UTC, dnanjunda requested changes
Looks better Parth! There are a few more changes needed:

1. Kind of a nitpick but make the send and continue buttons less rounded and the same width like in the figma:

Your code:
<img width="962" alt="button" src="https://user-images.githubusercontent.com/57281768/155095316-d17d0559-a401-4a0d-946c-b0fa8e91eb22.png">

Figma:
<img width="574" alt="button_figma" src="https://user-images.githubusercontent.com/57281768/155095346-a7c21218-e365-4d24-a4a8-ea65fc32ff05.png">

2. Add form validation to check that a team is selected (in the first component itself) and that the message box isn't empty (when they click send). For both cases, display red text above the component showing the error. So, if a team isn't selected, display "Please select a team to send the message to." If the message is empty, you can say "Message body cannot be blank."
3. For the thank you popup, increase the font size a bit and center it within the box as well.
4. For a specific range of screen width (750 to 900 px), the contact component overlaps with the navbar. You can either add a media query to reduce the width of the component for this range or make the width of the navbar be responsive. If possible, try the latter since the navbar is taking up a chunk of the screen anyway.
<img width="401" alt="contact" src="https://user-images.githubusercontent.com/57281768/155096627-2f1543d7-bb0f-4b69-bd3e-67d17bb2a839.png">

5. For some of the smaller screen sizes, the dropdown text overflows. Same with the text in the thank you popup:
<img width="310" alt="mobile_contact" src="https://user-images.githubusercontent.com/57281768/155096293-570a06e5-cd1c-4ba9-a85a-915b9db3bf4d.png">

6. Increase the width of the thank you popup on mobile screens to almost the same as the component. This looks a bit weird:
<img width="321" alt="contact_popup" src="https://user-images.githubusercontent.com/57281768/155097176-2e529267-0ff6-4618-ad3a-d79d7ecaa2e5.png">

2022-02-25 02:35 UTC, petabite requested changes
Nice! Responsiveness is looking good on my end.

Some things I noticed:
- Some cursors (see comments)
- Font size on mobile view (see comment)
- The form validation only works the first time. If I send the message the first time successfully and click the "X" in the top right corner and try to send an empty message, it lets me send.

But other than that, it's looking good!

2022-02-25 02:35 UTC, petabite commented on client/src/css/contactStyles.css
> +  text-align: center;
```suggestion
  text-align: center;
  cursor: pointer;
```
UX improvement: This should make it more obvious that the "Continue" button is clickable.

2022-02-25 02:35 UTC, petabite commented on client/src/css/contactStyles.css
> +  border: none;
```suggestion
  border: none;
  cursor: pointer;
```

2022-02-25 02:35 UTC, petabite commented on client/src/css/contactStyles.css
> +  border: none;
```suggestion
  border: none;
  cursor: pointer;
```

2022-02-25 02:35 UTC, petabite commented on client/src/css/contactStyles.css
> +  left: 2%;
```suggestion
  left: 2%;
  cursor: pointer;
```

2022-02-25 02:35 UTC, petabite commented on client/src/css/contactStyles.css
> +    font-size: min(10px, 4vw);
On mobile views, the font is extremely small:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/24444266/155641526-d45a99c0-fc06-40c8-884c-18acb2e5f904.png">

It looked better when I did this though:
```suggestion
    font-size: max(10px, 4vw);
```
(but you may have a better solution)

2022-02-25 02:44 UTC, petabite commented on package.json
> +    "styled-components": "^5.3.3"
```suggestion
```
Oops, looks like you added `styled-components` to the backend package.json again.

2022-02-27 02:03 UTC, dnanjunda requested changes
Besides the things Philip noted above, here's what I noticed:

1. For the error text, I meant put it above the whole component not just the message box. The placement looks a bit weird right now.
2. Also, the error for selecting a team should be within the first component itself (the one that asks you to choose a team). Don't let the user continue without selecting a team.
3. Not sure what you changed, but the font size is too small now on mobile screens. This is mainly the text in the message box, the dropdown, and the buttons. 
4. For the thank you popup, make it wider for ipad/tablet screens (750 to 1000 px) like you did for mobile. It looks squished right now:
<img width="403" alt="thankyou_popup" src="https://user-images.githubusercontent.com/57281768/155865183-c121efae-20c4-41df-a884-41d0ef5f422c.png">

2022-03-08 17:21 UTC, petabite approved these changes
👌

2022-03-09 00:03 UTC, dnanjunda approved these changes
LGTM! Great work Parth

2022-03-09 00:04 UTC, merged