Pending Applications Page
TritonSE/TAP-Foster-Dog-Matching pull request #20
Opened 2022-02-07 01:27 UTC by petabite

### Administrative Info
[GitHub Issue #16]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
- add Pending Applications page for admin view

### Testing
- manually changed the `role` variable to make sure each view displayed correctly

### Confirmation of Change 
TODO

2022-03-30 08:07 UTC, parth4apple requested changes
Looks good but I noticed a few minor issues.

1) The dropdown disappears after the Table div's height ends. I saw that this is scrollable so you can still get to everything in the dropdown, but users might not see that. Maybe make the height of the table component longer or change its overflow handling.
<img width="1433" alt="Screen Shot 2022-03-30 at 12 41 30 AM" src="https://user-images.githubusercontent.com/72187062/160779513-872c793d-0fdf-4f9a-9414-9dbba24bdb79.png">

2) On mobile view, the table is to the right a certain amount, which looks kind of odd. There aren't mobile views for this on the figma so it could work, but to make the table left aligned just change the dashboardbody.css media query on line 16 to a different padding value
<img width="686" alt="Screen Shot 2022-03-30 at 12 41 57 AM" src="https://user-images.githubusercontent.com/72187062/160780858-cfc35ef9-38b1-4c0a-86f8-7d4433742ef4.png">

3) I noticed some weird behavior when scrolling (not on mobile view). The header slides with the table. I think the problem here lies more in the header file and its css.

https://user-images.githubusercontent.com/72187062/160781517-005d3c42-e558-4a42-9356-18cd7392b138.mov

Clean code by the way!

2022-03-31 01:15 UTC, parth4apple approved these changes

2022-03-31 02:58 UTC, dnanjunda requested changes
Looks nice Philip! Just a couple things to fix:

1. All of the pages have some extra scroll. I think this is because of the recent changes to the header and defaultbody components.

https://user-images.githubusercontent.com/57281768/160967160-f3945458-62f6-4501-8505-114ca04c0649.mov


2. Add a bit of padding on the right end of the table when the table doesn't fit in the screen just to be consistent.

<img width="530" alt="table_padding" src="https://user-images.githubusercontent.com/57281768/160967206-5f45a9b1-f143-470c-b50f-611422efc37f.png">

2022-03-31 07:40 UTC, dnanjunda approved these changes
LGTM! Nice work Philip

Note: The extra scroll bug will be fixed in a future PR (Application page).

2022-03-31 07:40 UTC, merged