Feature/parth4apple/user schema routes
TritonSE/TAP-Foster-Dog-Matching pull request #25
Opened 2022-02-24 01:11 UTC by parth4apple

### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- I added user schemas and routes.

### Testing
How did you confirm your changes worked? 
- I used postman to test creating a new user and logging in.

2022-03-07 07:27 UTC, jacobayu approved these changes
lgtm very cool

2022-04-10 21:52 UTC, petabite commented on models/user.js
> +    },
Since we are using Firebase for authentication now, I don't think we need to save passwords.

2022-04-12 06:18 UTC, dnanjunda requested changes
Looks nice Parth! There's a few changes needed:

1. In your validators variable, add a check to see if the last active date is in this format: "MM/DD/YY". Also, make sure to check that the email field is in email address format.
2. For all routes, when there's an error (when the user couldn't be validated, when the user couldn't be created, etc.), send a res status 500 message instead of throwing an error.
3. I realized we need one more route for users to retrieve a specific user by ID. Can you add this route? I'll add the details for this route in the Project Details doc.

2022-04-21 05:30 UTC, petabite approved these changes
👌

2022-04-23 20:50 UTC, dnanjunda approved these changes
LGTM!

2022-04-23 20:50 UTC, merged