Foster Application Page
TritonSE/TAP-Foster-Dog-Matching pull request #33
Opened 2022-03-31 18:18 UTC by petabite

### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
- added ApplicationProgress and various Form components
- created Foster Application and Foster Agreement page (`/application`)
- fixed scrolling issue noted in #20 

### Testing
- tested form validation works
- tested view changes appropriately on mobile breakpoint

### Confirmation of Change 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24444266/161122905-73df1f7d-75b1-4f56-8e01-91544f82b064.png">

2022-03-31 18:23 UTC, petabite commented on client/src/pages/Application.js
> +    // setView("agreement"); // uncomment this to see the foster agreement w/o filling out the form
You can use this to see the foster agreement

2022-04-02 06:18 UTC, dnanjunda requested changes
Looks clean Philip! Here's some things I noticed though:
1. I think you can remove the increment/decrement buttons for the zipcode field. They're not too useful there.
2. There seems to be a bit of scroll on the overall page. Can you get rid of this and have the form section extend all the way down to the bottom of the screen? Same with the form agreement section. Should look like this:
<img width="1106" alt="application_page" src="https://user-images.githubusercontent.com/57281768/161369380-500a0b43-ed5b-4388-bd85-581b3bdb5f99.png">

3. When the user inputs "n/a" for landlord, make the landlord phone number and email fields optional. Or you can allow "n/a" inputs for those as well. I think the former would be ideal though.
4. Can you add an "Exit" button in the top left corner similar to the design? This should just redirect to the dashboard page.
5. I think you can also remove the scrollbar within the form section since we have the trackbar on the left side. Let me know what you think about this though.

2022-04-02 23:35 UTC, willji0023 requested changes
Everything looks really great! Here's just some minor things I noticed:

1. I think the margins around the milestone text "Application Submitted" on Mobile view might be a little squished and could be increased a tad on either side, if possible. 
![image](https://user-images.githubusercontent.com/23545972/161404337-2403cfef-b5e4-45f2-96d3-defa31a5d7fe.png)

2. It would also be nice if the icon of the calender button on the date field for the Foster Agreement form matched the one on the Figma.

3. Not sure if we plan on using some sort of signature box for the Foster Agreement form, but if so maybe for now we could at least increase the size of the text-box like in the Figma? Maybe @dnanjunda can fact-check me on this.
![image](https://user-images.githubusercontent.com/23545972/161404432-35e9f97b-49a6-41bb-8681-f651031ab0b9.png)

2022-04-03 21:25 UTC, dnanjunda commented
> 
Yes, we'll leave the signature box as is for now until I talk to the client about it.

2022-04-03 23:33 UTC, petabite commented
> 2. It would also be nice if the icon of the calender button on the date field for the Foster Agreement form matched the one on the Figma.

Yeah, the icon you see comes from the browser's default date input implementation. Would it be okay if we left it as the default, @dnanjunda?

2022-04-06 04:16 UTC, willji0023 approved these changes
Everything looks really clean! And looks like all of both Dhanush's and my comments were addressed. LGTM

2022-04-06 05:19 UTC, dnanjunda approved these changes
LGTM! Great work Philip

2022-04-06 05:19 UTC, merged