Feature/willji0023/calendar page
TritonSE/TAP-Foster-Dog-Matching pull request #73
Opened 2022-05-18 11:04 UTC by willji0023

### Administrative Info
[GitHub Issue #51]

### Changes
What changes did you make?
- Created components for Calendar page.
- Styled Calendar page for both desktop and mobile views.

### Testing
How did you confirm your changes worked? 
- Viewed and tested components manually at different screen widths
- Compared style to Figma

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Calendar Page|
| --- |
|![image](https://user-images.githubusercontent.com/23545972/169024285-9d98e849-8d58-4bb4-aecd-c843c94920a4.png)|

| Weekly Schedule Adder|
| --- |
|![image](https://user-images.githubusercontent.com/23545972/169024441-f1deb7ed-9b46-44b7-a3d5-55d4bc619aa4.png)|

2022-05-19 20:38 UTC, dnanjunda requested changes
Looks great Will! Really minor things here:

1. The title for the right side component should be "Schedules" instead of "Times Available."
2. There's a tiny bit of scroll within the popup. Can you increase its height a bit to get rid of it?
<img width="1440" alt="Screen Shot 2022-05-19 at 1 30 14 PM" src="https://user-images.githubusercontent.com/57281768/169399811-e6ad7ede-69cc-428b-8638-b6f7ffe6cce8.png">

3. Right now, the user has to add a time manually by typing it in. Can you make it a dropdown with 30 minute intervals? It can look like this:
<img width="1059" alt="Screen Shot 2022-05-19 at 1 31 24 PM" src="https://user-images.githubusercontent.com/57281768/169399756-cce926f1-2041-4020-9b77-c0ae06395f43.png">

4. This isn't super important but the first row of the calendar seems off position when the whole row isn't filled.
<img width="1041" alt="Screen Shot 2022-05-19 at 1 32 35 PM" src="https://user-images.githubusercontent.com/57281768/169399637-a1f7a951-cbea-4ecd-8122-80c0ebdc170e.png">

2022-05-23 22:52 UTC, jacobayu requested changes
Very poggers Will, this looks really good. Just one small thing I noticed during the mobile views is that some of the meetings are overflowing out of the meeting component. I'm not sure if you want to make it scroll instead

<img width="262" alt="Screen Shot 2022-05-23 at 3 50 44 PM" src="https://user-images.githubusercontent.com/57156703/169917225-a3c87749-a35e-448d-800d-2a612d0c6a6b.png">

2022-05-24 02:22 UTC, jacobayu approved these changes

2022-05-24 06:25 UTC, dnanjunda approved these changes
LGTM!

2022-05-24 06:25 UTC, merged