Integrate Foster/Admin Application Page
TritonSE/TAP-Foster-Dog-Matching pull request #76
Opened 2022-05-18 19:41 UTC by petabite

### Administrative Info
[GitHub Issue #58]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
- integrate application page components for foster/admin
- connect the application page to the backend

### Testing
How did you confirm your changes worked? 
- TODO

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

2022-05-25 00:29 UTC, petabite commented on client/src/pages/Application/index.js
> +  const role = "foster";
Set this to `"foster"` or `"admin"` to see either application view.

2022-05-25 00:31 UTC, petabite commented on client/src/pages/Application/FosterView/Step4.js
> +  ]);
Set this useState to an empty array (`[]`) to see the "Still looking for matches..." state

2022-05-27 00:33 UTC, dnanjunda requested changes
Looking good Philip! Here's what I noticed:

1. The border width for most of the components is pretty inconsistent. I know Jacob and others have worked on this as well but can you try to make it more consistent across stages? It's mainly this Meetings component:
<img width="1439" alt="Screen Shot 2022-05-26 at 5 28 00 PM" src="https://user-images.githubusercontent.com/57281768/170605132-7ca168b0-fe74-491b-8528-402046466879.png">

Other components look like this:
<img width="1440" alt="Screen Shot 2022-05-26 at 5 28 25 PM" src="https://user-images.githubusercontent.com/57281768/170605140-a114e920-256d-46d6-ad1d-5a5c09bd5151.png">

2. For the "Interview Confirmed" component on the foster side, should it have the interview location as well? Same thing for this component in the home screen and meet & greet stages.
Your code:
<img width="1439" alt="Screen Shot 2022-05-26 at 5 09 10 PM" src="https://user-images.githubusercontent.com/57281768/170603546-9365a58f-0749-4d44-a9fa-7636acde72ac.png">

Design:
![Screen Shot 2022-05-26 at 5 10 12 PM](https://user-images.githubusercontent.com/57281768/170603556-211a1460-91d7-49de-847d-5cebe44612a2.png)

3.  For the first step on the admin side, it should display this loading component instead of what you have right now. You actually have this under step 2, so just move it to step 1.
![Screen Shot 2022-05-26 at 5 20 51 PM](https://user-images.githubusercontent.com/57281768/170604486-b8587aa9-52e7-4a1b-b74b-a7342a39d666.png)

4. For step 6 on admin side, I know we don't have the Foster Profile component yet, but can you add the Dog Profile component there?
5. For all these components, can you add some padding below them so that they look like this? Maybe you just need to modify DefaultBody for this.
![Screen Shot 2022-05-26 at 5 29 03 PM](https://user-images.githubusercontent.com/57281768/170605322-33fbd8e7-18ad-4b64-a6d8-54debf631804.png)

2022-05-27 06:24 UTC, petabite commented on client/src/pages/Application/index.js
> +  const [applicationState, setApplicationState] = React.useState({ status: "" });
Set `status` to `"rejected"` to see application rejected state

2022-05-30 22:05 UTC, parth4apple requested changes
Pretty awesome PR Philip. Here's some things I noticed.

Foster View:
1. On taller viewports, this component looks a little bit streched. Maybe limit the height of the container to the height of the image for non-mobile viewports.
<img width="2048" alt="Screen Shot 2022-05-30 at 2 39 39 PM" src="https://user-images.githubusercontent.com/72187062/171061542-453c1c22-201e-4718-a38c-976dbfea8cbc.png">
 
2. Similar issue with this component, the status update component on step 4, and foster resources component on step 6. The container div expands beyond what it needs to so it looks a little bit funky. Not a big deal if the css is too hard to fix.
<img width="2048" alt="Screen Shot 2022-05-30 at 2 41 27 PM" src="https://user-images.githubusercontent.com/72187062/171061673-3e18f479-05b8-4bb8-b63b-67831923ef2a.png">
 
<img width="2048" alt="Screen Shot 2022-05-30 at 2 43 36 PM" src="https://user-images.githubusercontent.com/72187062/171061839-b962697f-0a2d-4ee9-9a79-67993a92c6ed.png">

<img width="1540" alt="Screen Shot 2022-05-30 at 2 45 46 PM" src="https://user-images.githubusercontent.com/72187062/171062003-f2613f15-42c9-461d-a108-b9aaf9b8c9fd.png">

3. When you click adopt in step 6, it says "we are so excited for you to become a foster fail!". Maybe replace "fail" with "success". I think this might be a mistake in the figma.

<img width="2048" alt="Screen Shot 2022-05-30 at 2 49 51 PM" src="https://user-images.githubusercontent.com/72187062/171062279-7831ae2e-17fb-4222-a0b0-e361567b0a57.png">
 
4. The content overflows on some ipad viewports for this component. I think it's because the buttons are statically sized.
<img width="1068" alt="Screen Shot 2022-05-30 at 3 03 14 PM" src="https://user-images.githubusercontent.com/72187062/171063229-79f5b91c-d6a8-4c79-a035-276e05f14522.png">


Admin View:
1. If there was a blurred background on the pass fail component or even just a black border if a blur is too hard to do, it would look a lot cleaner. 

<img width="2048" alt="Screen Shot 2022-05-30 at 2 59 53 PM" src="https://user-images.githubusercontent.com/72187062/171062991-e988384b-6397-4e45-867f-13d1bcb5ca23.png">

2022-05-31 07:37 UTC, parth4apple commented
Hey Phillip, a lot better, but there are still some things to clean up.
Foster:

1. Follow up on number 4 in my previous code review, now all background div also overflows the page.
<img width="1049" alt="Screen Shot 2022-05-31 at 12 17 51 AM" src="https://user-images.githubusercontent.com/72187062/171114940-7bbfefe7-8833-43e3-bc0b-1b4b7479558d.png">

2. The message area gets too small in tablet viewports and the dog image looks too big. Try to have a  similar scaling behavior to the interview scheduling component, I think that looks pretty nice. This is minor so if it's too tedious to fix, then don't worry about it. 

<img width="1132" alt="Screen Shot 2022-05-31 at 12 19 29 AM" src="https://user-images.githubusercontent.com/72187062/171115268-f7e84ab4-b6d0-4ddc-9e21-1c42a0a96bd7.png">

 3. Add a little padding top.
<img width="880" alt="Screen Shot 2022-05-31 at 12 23 16 AM" src="https://user-images.githubusercontent.com/72187062/171115932-a1bf76e3-3bf9-4764-919b-3de35265105c.png">

4. Minor thing - the titles "status update" and "foster resources" are very small on tablet/mobile views (stage 4 content, stage 6 content).

<img width="690" alt="Screen Shot 2022-05-31 at 12 36 33 AM" src="https://user-images.githubusercontent.com/72187062/171118487-6cfaacf7-767e-47c5-b5bb-41df1e6408fc.png">

Admin:
1. Another minor thing - make the Interview info and after interview titles inline with each other. 
<img width="1726" alt="Screen Shot 2022-05-31 at 12 28 06 AM" src="https://user-images.githubusercontent.com/72187062/171117019-f756862d-08ba-414b-a4e1-a8d97c5081ba.png">

2. I think you refactoring the status update component to use flexbox modified the behavior of this page. The bottoms of each component do not match. If you add a little bit more whitespace to the bottom of the status update container in the meet and greet component, I think this should be fixed.

<img width="2048" alt="Screen Shot 2022-05-31 at 12 30 06 AM" src="https://user-images.githubusercontent.com/72187062/171117146-356313c1-89fb-4d61-95ab-dff1fdd8b239.png">

2022-06-19 20:06 UTC, parth4apple approved these changes
LGTM

2022-07-01 03:24 UTC, dnanjunda approved these changes
LGTM! Nice work!

2022-07-01 03:24 UTC, merged