Feature/jacobayu/interview info
TritonSE/TAP-Foster-Dog-Matching pull request #77
Opened 2022-05-19 21:36 UTC by jacobayu

### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- TODO

### Testing
How did you confirm your changes worked? 
- TODO

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

2022-05-24 03:21 UTC, dnanjunda requested changes
Looking nice Jacob! Here's what I noticed:

1. This component has a title that will be passed in so add a prop for that. Take a look at the designs for reference.
2. The input box has a blue outline when in focus. Can you remove that? Also, when an input field is in focus, we decided to make the border color the bright green used throughout the website. Take a look at Input.js (in the components folder on main) for an example.
3. The width of the black borders is a bit inconsistent. Make the border on the left and right always have the same width and the middle can take up the remaining space.
4. When the contingent button is removed, the width of the component decreases. Can you make it have the same width with and without the contingent button?

With contingent button:
<img width="1439" alt="Screen Shot 2022-05-23 at 8 03 52 PM" src="https://user-images.githubusercontent.com/57281768/169941105-c30ece77-75ae-4ee8-8a32-0a2ed8e87a58.png">

Without contingent button:
<img width="1438" alt="Screen Shot 2022-05-23 at 8 09 32 PM" src="https://user-images.githubusercontent.com/57281768/169941113-470ee313-e6c2-4b45-a9f6-10fa10855c80.png">

5. I'm not sure if Philip is working on the status update component so please check with him. It looks like you only need to decrease its height though.
6. Make the font size the same for the titles "Interview Info" and "After Interviews."

2022-05-27 19:08 UTC, petabite approved these changes
Nice, LGTM! Just one small thing I noticed:

2022-05-27 19:08 UTC, petabite commented on client/src/pages/Application.js
> +        </div>
Can you get rid of the `div` wrapping the `Meetings` component here so that the card can expand to take up the full width of the page?

2022-05-30 23:52 UTC, dnanjunda approved these changes
LGTM! Nice work Jacob

2022-05-30 23:53 UTC, merged