Feature/artyom2001/dog-card
TritonSE/TAP-Foster-Dog-Matching pull request #83
Opened 2022-05-29 19:13 UTC by artyom2001

### Administrative Info
[GitHub Issue #54 ]

### Changes
What changes did you make?
- Make dog card component
- Add responsive styling for various mobile devices

### Testing
How did you confirm your changes worked? 
- TODO

### Confirmation of Change 

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

2022-07-01 05:21 UTC, dnanjunda requested changes, later dismissed
Looking good! Really minor things here:

1. Can you try to space out the text below Background and Vetting Information to look more like this from the designs?

Design:
<img width="1175" alt="dog_design" src="https://user-images.githubusercontent.com/57281768/176828705-14bd6369-c253-4b84-83c3-e13f33eb8e00.png">

Your code:
<img width="1010" alt="dog_code" src="https://user-images.githubusercontent.com/57281768/176828714-25ae90e2-86a2-4a4f-8513-0d91d1b69000.png">

2. Since this is a pop up, we need an "X" button in the top left corner. Take a look at the screenshot above.
3. The component doesn't look great on mobile. Can you try to make it size down (at least to get rid of the horizontal scroll) on these smaller mobile screens?
<img width="373" alt="dog_mobile" src="https://user-images.githubusercontent.com/57281768/176828790-95707f79-269b-4b4a-bd2b-189bb8044c79.png">

2022-07-03 05:23 UTC, portoaj commented
1. According to the figma it seems like the card should be used for part 4 of the application process.
2.  The dog card shouldn't be commented out in the landing page
![image](https://user-images.githubusercontent.com/8219702/177026086-a588ce44-388a-4b86-9e64-4a4edab1084e.png)
3. It looks like the rightmost scrollbar is cutting into the border
4. The background shouldn't have a scrollbar unless it has enough content to warrant one I think

2022-12-01 20:12 UTC, sharmaadvay0 approved these changes
LGTM. You might need to resolve some merge conflicts.

2023-01-26 03:52 UTC, wllmwu approved these changes

2023-01-26 03:52 UTC, merged